### ISSUE TITLE
Upgrade box to jessie

### ISSUE THREAD

**Issue by sephii** [team-rawbot/rawbot-virtualization#10]
I created a WIP branch "jessie". I only took care of the python and postgresql roles which seem to be working. You won't be able to test for the moment because I still need to upload the box. Anyway, here's what's left to be done:

- [x] test & update roles
- [x] create virtualbox box
- [x] fix "halt" issue (see https://github.com/mitchellh/vagrant/issues/5497 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=751636)

**Comment by krtek4** [comment]
Great job thanks !

Concerning the systemd issue, we could maybe reinstall sysv in the box, it's not that complicated.

Also maybe we could take the opportunity to put most of the "base" packages directly in the box to gain some time ?

**Comment by sephii** [comment]
Maybe it could be worth going back to sysv since the bug doesn't seem to be about to be fixed soon.

As for the base packages I agree, but we should make sure we have a playbook for that, to make sure the same base packages are installed in every box.

**Comment by krtek4** [comment]
Reviewing the issue with the 'halting' it seems the fix is as simple as running those command once in the box :
    systemctl disable ssh.service
    systemctl enable ssh.socket

Maybe just add that to the provisioning and consider it done ?

**Comment by sephii** [comment]
I tried it on a local box but it didn't solve the issue for me.

**Comment by sephii** [comment]
Fixed in 81eff7c6f0cf4fb838cb51f6e514c3e067739cb7.
