### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by krtek4** [team-rawbot/rawbot-virtualization#11]
Currently, it is really hard to install a PHP version that is different than the one provided in the base distribution (Wheezy, soon Jessie).

Maybe we could provide a role to ease the pain ?

**Comment by krtek4** [comment]
A solution for wheezy might be this new role by @gnutix  :

# playbook.yml
- roles :
    - { role: dotdeb, repository: 'wheezy-php55' }
```

```# dotdeb/defaults/main.yml
---
repository: wheezy
```

```# dotdeb/tasks/main.yml
---
- name: APT | Add DotDeb repository
  apt_repository: repo='{{ item }}'
  with_items:
    - deb http://packages.dotdeb.org {{ repository }} all
    - deb-src http://packages.dotdeb.org {{ repository }} all
  tags: dotdeb
  sudo: yes

- name: APT | Install DotDeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg
  tags: dotdeb
  sudo: yes

- apt: update_cache=yes
  sudo: yes```

**Comment by gnutix** [comment]
@krtek4 Just tried with Jessie using `jessie` as default repository : works like a charm (installs `5.6.13` instead of `5.6.7`).

**Comment by krtek4** [comment]
@gnutix PHP 5.6.13 is the package from Debian ( https://packages.debian.org/jessie/php5 ).

The `jessie` repository of DotDeb contains a php7 package that installs php 7.0 which is currently not managed at all by the role.

**Comment by krtek4** [comment]
Jessie is "stuck" on php 5.6. However you can choose between 5.4, 5.5 and 5.6 on Wheezy.
