### ISSUE TITLE
Variable php_date_timezone is not configured into /etc/php5/cli/php.ini

### ISSUE THREAD

**Issue by jeanmonod** [team-rawbot/rawbot-virtualization#14]

**Comment by jeanmonod** [comment]
@krtek4 is that a bug? Or missing config? Could I ask @jonathanm10 to fix it?

**Comment by krtek4** [comment]
The default php.ini has no timezone set, feel free to add a template value and update the ini file already created :)

**Comment by jeanmonod** [comment]
@Jonathanm10 Can you take care of this? Thanks

**Comment by krtek4** [comment]
This should be fixed now that the php config is also copied for the CLI in the Jessie box.
