### ISSUE TITLE
Add aliases to use Highlights easily

### ISSUE THREAD

**Issue by krtek4** [team-rawbot/rawbot-virtualization#19]
http://www.andre-simon.de/doku/highlight/en/highlight.php

ask @Hywan, he has really nice ones on his laptop.

**Comment by Hywan** [comment]
See my custom alias here: https://github.com/Hywan/Dotfiles/blob/763e26edea2dd614b79d54f457c89ffe49ed3202/alias#L43.

**Comment by Hywan** [comment]
![screen shot 2015-08-10 at 11 02 17](https://cloud.githubusercontent.com/assets/946104/9165569/8247d184-3f50-11e5-84f5-a2496607ad13.png)

**Comment by Hywan** [comment]
Must have: `tail -f logs/swse/full_stream | hl xml`. Pure awesomeness :-].
