### ISSUE TITLE
Provisinonning first with python2 then switching to 3 does not work.

### ISSUE THREAD

**Issue by krtek4** [team-rawbot/rawbot-virtualization#24]
If you first provision a box with python 2 and later on decide to switch to python 3, you will have the following issue :

    TASK: [python | make symlink from pip-3.2 to pip] ***************************** 
    failed: [default] => {"failed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/usr/bin/pip", "size": 281, "src": "/usr/bin/pip-3.2", "state": "file", "uid": 0}
    msg: refusing to convert between file and link for /usr/bin/pip

Don't know what the best course of action is in this case, uninstall the other version ? force the symlink ?

@OdyX @sephii  what do you think ?

**Comment by sephii** [comment]
What about putting the symlink in `/usr/local/bin` instead? It should have precedence over `/usr/bin`. This would be less invasive, and afaik we only need that for Ansible's pip module. Another solution would be to skip the symlink creation entirely and explicitly set the `executable` option when using the `pip` module, but this would be quite annoying.

**Comment by krtek4** [comment]
It seems "risky" to me to have two different version of pip with the same binary name. Depending on the PATH, this could lead to some strange things.

Also, any script expect pip to be in `usr/bin` it will raises some nasty issues.

I think I would personally ensure that only the 2 or 3 versions of the package is installed and uninstall the other.

**Comment by sephii** [comment]
In most cases we need to have both Python 2 and 3 installed in order to use tox, so being able to have only one version of Python would be very limiting.

**Comment by krtek4** [comment]
I am not saying removing python2 entirely, but just the packages that were installed by the role : https://github.com/team-rawbot/rawbot-virtualization/blob/master/provisioning/roles/python/tasks/main.yml#

I think having the pip and virtualenv version for both python2 and python3 will only lead to issues and confusion. Even more if `/usr/bin/pip` is v2 and `/usr/local/bin/pip` is v3.

I would say there should be only one pip and one virtualenv at anytime on the system.

BTW, we should also maybe fill a debian bug so that the pip version can be managed via [debian alternatives][https://wiki.debian.org/DebianAlternatives]. wdyt ?

**Comment by sephii** [comment]
Maybe creating a symlink `/usr/bin/pip` for pip3 is just not the right way to do it. At the moment we're using the `pip` module only in the `django` role, and we could easily set the pip version to use (via the `executable` parameter of the pip module) to create a Python 2 or Python 3 virtualenv depending on the Python version set in the parameters.

Filing a bug to use alternatives to manage pip would mean doing the same to manage Python and this would be quite a big change I guess.

If you think having pip3 available as `pip` is that important, I agree that we could just make sure only Python 2 or Python 3 pip is installed and create a symlink if necessary. This would probably be the easiest solution.

**Comment by sephii** [comment]
After more thinking I don't think `tox` will be able to create the necessary virtualenv for Python 2 if Python 2's pip is not installed. In my opinion we just shouldn't do anything about it.

**Comment by sephii** [comment]
This should be fixed by https://github.com/team-rawbot/rawbot-virtualization/commit/facd8deced97fa3d0a178a72e7ea4147b781274d.

Note that when switching to Python 3 your virtualenvs (if any) won't be recreated so you'll have to do destroy them and re-provision.

**Comment by sephii** [comment]
Also note that the `django` role won't work on wheezy because of the unavailability of the `python3-venv` package. Another solution would be to pass the `virtualenv_python` option when creating the virtualenv but this will unfortunately only be supported starting in Ansible 2.0.

Anyway since wheezy doesn't have Python 3.4 and Django 1.9 will only support Python >= 3.4 I don't think this is much of an issue.

**Comment by krtek4** [comment]
@sephii concerning your commit facd8deced97fa3d0a178a72e7ea4147b781274d , are you sure the installation of python3 venv on Wheezy is correct ?

Since both python2 and python3 are installed, it seems to me that you have to precise the pip executable to use to target python3.

Also, I don't get the issue with Django and Wheezy, are we not installing virtualenv through pip there ?

Maybe talk about that IRL next week ?

**Comment by sephii** [comment]
There's no Python 3 virtualenv package on Wheezy. So we install the Python 2 package and we can then specify which Python interpreter should be installed in the virtualenv when creating it. We might run a few additional tests to ensure it's working on Wheezy, especially since Ansible's `pip` module only allows the `virtualenv_python` parameter to be passed since version 2.0.

As for the issue with Django and Wheezy, the issue is just what I mentioned: we can't use the `virtualenv_python` option when creating the virtualenv because it's only available in Ansible >= 2.0.

Maybe we could install `virtualenv` through pip though. Let's discuss that IRL next week.

**Comment by krtek4** [comment]
Closing this as the inital issue was resolved. See #29 for the remaining issue of python3 on Wheezy
