### ISSUE TITLE
Ansible error [Errno 8] Exec format error

### ISSUE THREAD

**Issue by jeanmonod** [team-rawbot/rawbot-virtualization#8]
Hi guys,

When I do my first vagrant up:

    [dj]/Users/dj/Projects/uber|master>vagrant provision
    /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /Users/dj/Projects/uber/. in PATH, mode 040766
    /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /Users/dj/Projects/uber/. in PATH, mode 040766
    ==> default: Running provisioner: ansible...

I got this error

    ERROR: problem running /Users/dj/Projects/uber/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory --list ([Errno 8] Exec format error)
    Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

I would like to fix it, but I have not error output. How can I increase the log level of the output? I just take a look at the [README.md](https://github.com/team-rawbot/rawbot-virtualization/blob/master/README.md) but I didn't find info about that.

Thanks for support

**Comment by krtek4** [comment]
This is an issue either with Ansible directly, or the installed version of Ansible on your system ;)

Please check that `/Users/dj/Projects/uber/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory` is a valid executable.

Eventually delete the whole directory `/Users/dj/Projects/uber/.vagrant` and try `vagrant up` again.

In the meantime, closing this...

**Comment by jeanmonod** [comment]
In fact it was the opposite! The `vagrant_ansible_inventory` should NOT be executable! So I simply fix the issue with a

    chmod -x /Users/dj/Projects/uber/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory

Is this something that can be fixed into this virtualization project?

**Comment by krtek4** [comment]
No... This was your mistake ;)

**Comment by madteckhead** [comment]
So obscure but this helped me too thanks!!

**Comment by schlueter** [comment]
Thanks, this was helpful. This seems like a bug in Vagrant's handling of the its inventory file. Next person to encounter it should open a issue on Vagrant.

**Comment by xiaochenchen86** [comment]
check your script，whether to include "#!/usr/bin/env python"
