### ISSUE TITLE
Improve front-end develpement workflow

### ISSUE THREAD

**Issue by LeBenLeBen** [team-rawbot/rawbot-virtualization#9]
As a front-end developer, it would be great if I could have the usual tools we use pre-installed and pre-configured with the provisioning.

In all projects, we use Sass, most of the time with Compass. Watching for changes in these files and compiling on the fly without having to start any additional command would be great. That would require to define a source and destination folder or something similar in the configuration as it can changes depending on project technology.

Other tools like LiveReload, JavaScript concat & uglify, combine media queries, SVG optim would be awesome but less important for now. It might worth having a look at how we could integrate Gulp to manage all this in the same place and in a similar way across all projects.

**Comment by jeanmonod** [comment]
+1 Let's install guard and hologram! @krtek4 you have already do that some months ago, isn't it ;)

**Comment by krtek4** [comment]
I started something, but never finished we didn't need it at the time. Like I already said to Ben, I'll try to have a look quickly :)

**Comment by sephii** [comment]
A potential blocker for this is that file monitoring is really wobbly with NFS.

**Comment by krtek4** [comment]
true !

Maybe a switch to rsync first ? I also heard there are "new" solutions to this speed issues with some kind of daemon (a tweet from dasrecht)

**Comment by LeBenLeBen** [comment]
Another way to go could be http://www.browsersync.io/

**Comment by LeBenLeBen** [comment]
The framework is temporarily located here: https://gitlab.liip.ch/liip/luff

* Node + NPM
* Gulp global
* Libsass
* (Yeoman)

**Comment by LeBenLeBen** [comment]
I’ve made some tests into a box today by manually installing gulp and browsersync. It seems to work pretty well. I just had to add `actimeo=1` to the mount parameters of synced folder to speed up the refresh rate. Otherwise it take around 20 seconds to detect changes in the files. With this parameter its only 1 second.

Here’s the article who guided me to this solution: https://www.jverdeyen.be/vagrant/speedup-vagrant-nfs/

**Comment by krtek4** [comment]
Some kind of implementation has been started in PR #26

**Comment by sephii** [comment]
Now we have the `gulp` role along with browsersync and sass support, I guess we can close this one @LeBenLeBen ?

**Comment by LeBenLeBen** [comment]
Yup 🖖🏻
